"""
Advisor page — grounded deck analysis (Phase 1: analysis mode on Gemini).

Pick a deck and a skill; the app builds a database-grounded context, asks the
model for schema-constrained suggestions, and validates them before display
(dashboard_lib/advisor/README.md). Computed numbers and model opinion are
shown separately; suggestions that failed verification sit collapsed under a
badge, never hidden. Read-only: nothing here writes to the collection.
"""
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import streamlit as st

from dashboard_lib import db, loaders
from dashboard_lib import card_view as cv
from dashboard_lib.advisor import analysis
from dashboard_lib.advisor.context import build_deck_context
from dashboard_lib.advisor.providers import GeminiProvider, ProviderError

cv.setup_page("Advisor · MTG Dashboard", "🧠")

db.require_db()
conn = db.get_connection()

st.title("🧠 Advisor")
st.sidebar.header("Advisor")
db.refresh_data_button()

decks = loaders.load_decks_df(conn)
if decks.empty:
    st.info("No decks yet.")
    st.stop()

deck_id = st.selectbox("Deck", decks["deck_id"], format_func=lambda i: decks.set_index("deck_id").loc[i, "name"])
skill = st.selectbox("Skill", list(analysis.SKILLS))

try:
    provider = GeminiProvider()
except ProviderError as e:
    st.error(str(e))
    st.stop()
st.sidebar.caption(f"Model: Gemini · {provider.model}")

ctx = build_deck_context(conn, int(deck_id))

st.subheader("Computed from your database")
s = ctx.stats
c1, c2, c3, c4 = st.columns(4)
c1.metric("Cards", s["total_cards"])
c2.metric("Lands", s["lands"])
c3.metric("Avg CMC (nonland)", s["avg_cmc"])
c4.metric("Candidates offered", len(ctx.candidates))
st.caption("Role counts come from oracle-text heuristics, so treat them as a cross-check, not gospel.")
st.json({k: s[k] for k in ("curve", "pips", "roles")}, expanded=False)

if st.button("Analyse deck", type="primary"):
    with st.spinner(f"Asking {provider.model}…"):
        st.session_state["advisor_result"] = (int(deck_id), analysis.run_analysis(provider, ctx, skill))

saved = st.session_state.get("advisor_result")
if not saved or saved[0] != int(deck_id):
    st.stop()
res = saved[1]
tot = st.sidebar
tot.metric("Tokens (last run)", f"{res.input_tokens + res.output_tokens:,}",
           help=f"{res.input_tokens:,} in / {res.output_tokens:,} out (output includes hidden thinking)")

if res.error:
    st.error(res.error)
    st.stop()

ck = res.checked
st.subheader("Model opinion")
st.caption("Generated by the model — interpretation, not fact.")
st.write(ck.summary)
left, right = st.columns(2)
left.markdown("**Strengths**\n" + "\n".join(f"- {t}" for t in ck.strengths))
right.markdown("**Weaknesses**\n" + "\n".join(f"- {t}" for t in ck.weaknesses))


def show_item(i):
    d = i.data
    if i.kind == "cut":
        st.markdown(f"**Cut {d.get('card')}** — {d.get('reason')}")
    else:
        st.markdown(f"**Add {d.get('card')}** (replacing {d.get('replaces')}) — {d.get('reason')}")
    st.caption(f"“{d.get('evidence_quote')}” · roles: {', '.join(d.get('roles') or []) or 'none'}")
    for v in i.violations:
        st.warning(v)


verified = [i for i in ck.items if i.verified]
unverified = [i for i in ck.items if not i.verified]
st.subheader(f"Suggestions ({len(verified)} verified)")
st.caption("Verified: card names exist, quotes match stored oracle text, roles agree with computed tags. "
           "That proves the facts are real, not that the advice is right."
           + (" One retry was needed." if res.retried else ""))
for i in verified:
    show_item(i)
if not verified:
    st.write("No verified suggestions.")
if unverified:
    with st.expander(f"⚠️ Unverified ({len(unverified)}) — failed a check, use with caution"):
        for i in unverified:
            show_item(i)
