"""
Advisor page — grounded deck analysis and chat (Phase 3: analysis mode plus
tool-based chat, both on Gemini).

Analysis mode: pick a deck and a skill; the app builds a database-grounded
context, asks the model for schema-constrained suggestions, and validates
them before display (dashboard_lib/advisor/README.md). Computed numbers and
model opinion are shown separately; suggestions that failed verification sit
collapsed under a badge, never hidden.

Chat mode: free-form conversation; the model calls read-only tools
(dashboard_lib/advisor/tools.py) to look up cards and decks, and every card
it mentions is checked against the database afterwards (chat.py, guard.py).
Gated off for any provider that doesn't declare `capabilities.tools`.

Read-only throughout: nothing on this page writes to the collection.
"""
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import streamlit as st

from dashboard_lib import db, loaders
from dashboard_lib import card_view as cv
from dashboard_lib.advisor import analysis, chat
from dashboard_lib.advisor.context import build_deck_context
from dashboard_lib.advisor.providers import GeminiProvider, ProviderError


def show_analysis_item(i):
    d = i.data
    if i.kind == "cut":
        st.markdown(f"**Cut {d.get('card')}** — {d.get('reason')}")
    else:
        st.markdown(f"**Add {d.get('card')}** (replacing {d.get('replaces')}) — {d.get('reason')}")
    st.caption(f"“{d.get('evidence_quote')}” · roles: {', '.join(d.get('roles') or []) or 'none'}")
    for v in i.violations:
        st.warning(v)


def run_analysis_tab(conn, decks, provider):
    deck_id = st.selectbox("Deck", decks["deck_id"], format_func=lambda i: decks.set_index("deck_id").loc[i, "name"])
    skill = st.selectbox("Skill", list(analysis.SKILLS))

    ctx = build_deck_context(conn, int(deck_id))

    st.subheader("Computed from your database")
    s = ctx.stats
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Cards", s["total_cards"])
    c2.metric("Lands", s["lands"])
    c3.metric("Avg CMC (nonland)", s["avg_cmc"])
    c4.metric("Candidates offered", len(ctx.candidates))
    st.caption("Role counts come from oracle-text heuristics, so treat them as a cross-check, not gospel.")
    st.json({k: s[k] for k in ("curve", "pips", "roles")}, expanded=False)

    if st.button("Analyse deck", type="primary"):
        with st.spinner(f"Asking {provider.model}…"):
            st.session_state["advisor_result"] = (int(deck_id), analysis.run_analysis(provider, ctx, skill))

    saved = st.session_state.get("advisor_result")
    if not saved or saved[0] != int(deck_id):
        return
    res = saved[1]
    st.sidebar.metric("Tokens (last analysis)", f"{res.input_tokens + res.output_tokens:,}",
                       help=f"{res.input_tokens:,} in / {res.output_tokens:,} out "
                            "(output includes hidden thinking)")

    if res.error:
        st.error(res.error)
        return

    ck = res.checked
    st.subheader("Model opinion")
    st.caption("Generated by the model — interpretation, not fact.")
    st.write(ck.summary)
    left, right = st.columns(2)
    left.markdown("**Strengths**\n" + "\n".join(f"- {t}" for t in ck.strengths))
    right.markdown("**Weaknesses**\n" + "\n".join(f"- {t}" for t in ck.weaknesses))

    verified = [i for i in ck.items if i.verified]
    unverified = [i for i in ck.items if not i.verified]
    st.subheader(f"Suggestions ({len(verified)} verified)")
    st.caption("Verified: card names exist, quotes match stored oracle text, roles agree with computed tags. "
               "That proves the facts are real, not that the advice is right."
               + (" One retry was needed." if res.retried else ""))
    for i in verified:
        show_analysis_item(i)
    if not verified:
        st.write("No verified suggestions.")
    if unverified:
        with st.expander(f"⚠️ Unverified ({len(unverified)}) — failed a check, use with caution"):
            for i in unverified:
                show_analysis_item(i)


def run_chat_tab(conn, provider):
    st.caption("Free-form chat. The assistant can look up cards and decks from your database; "
               "it cannot change anything.")
    if not provider.capabilities.tools:
        st.info(f"{provider.name} does not support tool calling, so chat mode is off for it.")
        return

    history_key = "advisor_chat_history"
    st.session_state.setdefault(history_key, [])

    for turn in st.session_state[history_key]:
        with st.chat_message(turn["role"]):
            st.write(turn["content"])
            if turn.get("tool_log"):
                with st.expander(f"🔧 Tool calls ({len(turn['tool_log'])})"):
                    for t in turn["tool_log"]:
                        st.caption(f"`{t['name']}({t['args']})`")
                        st.json(t["result"], expanded=False)
            if turn.get("unverified"):
                with st.expander(f"⚠️ Unverified mentions ({len(turn['unverified'])})"):
                    for v in turn["unverified"]:
                        st.warning(v)

    if st.button("Clear chat", disabled=not st.session_state[history_key]):
        st.session_state[history_key] = []
        st.rerun()

    prompt = st.chat_input("Ask about your decks or collection")
    if not prompt:
        return
    st.session_state[history_key].append({"role": "user", "content": prompt})
    raw_messages = [{"role": t["role"], "content": t["content"]} for t in st.session_state[history_key]]
    with st.spinner(f"Asking {provider.model}…"):
        res = chat.run_chat_turn(provider, conn, raw_messages)
    if res.error:
        st.session_state[history_key].append({"role": "assistant", "content": f"⚠️ {res.error}"})
    else:
        unverified = [f"{m.data.get('card')}: {v}" for m in res.checked.mentions for v in m.violations]
        st.session_state[history_key].append({
            "role": "assistant", "content": res.checked.answer,
            "unverified": unverified, "tool_log": res.tool_log,
        })
    st.rerun()


cv.setup_page("Advisor · MTG Dashboard", "🧠")

db.require_db()
conn = db.get_connection()

st.title("🧠 Advisor")
st.sidebar.header("Advisor")
db.refresh_data_button()

decks = loaders.load_decks_df(conn)
if decks.empty:
    st.info("No decks yet.")
    st.stop()

try:
    provider = GeminiProvider()
except ProviderError as e:
    st.error(str(e))
    st.stop()
st.sidebar.caption(f"Model: Gemini · {provider.model}")

tab_analysis, tab_chat = st.tabs(["Analysis", "Chat"])
with tab_analysis:
    run_analysis_tab(conn, decks, provider)
with tab_chat:
    run_chat_tab(conn, provider)
